PRODUCTS = [
    # ---------------- Hijama Suction Gun ----------------
    {
        "id": "hijama-vacuum-gun-premium-abs",
        "name": "Hijama Vacuum Gun | Premium ABS Imported Suction Gun",
        "category": "Hijama Suction Gun",
        "price": 269,
        "old_price": 349,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Hijama vacuum gun for cupping therapy. Premium ABS imported suction gun.",
        "keywords": ["hijama", "vacuum gun", "suction gun", "cupping", "manual pump"],
        "product_url": "/product/hijama-vacuum-gun-premium-abs",
        "image_url": ""
    },
    {
        "id": "hijama-therapy-gun-strong-suction",
        "name": "Hijama Therapy Gun | Premium Imported Quality Strong Suction",
        "category": "Hijama Suction Gun",
        "price": 253,
        "old_price": 460,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Cupping vacuum pump with strong suction for hijama and cupping therapy tools.",
        "keywords": ["hijama", "therapy gun", "strong suction", "cupping vacuum pump"],
        "product_url": "/product/hijama-therapy-gun-strong-suction",
        "image_url": ""
    },
    {
        "id": "hijama-vacuum-therapy-gun",
        "name": "Hijama Vacuum Therapy Gun",
        "category": "Hijama Suction Gun",
        "price": 259,
        "old_price": 288,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Premium-grade ABS plastic, strong suction, ergonomic grip, lightweight and portable. Compatible with standard cupping cups.",
        "keywords": ["hijama", "vacuum therapy gun", "abs plastic", "portable", "cupping"],
        "product_url": "/product/hijama-vacuum-therapy-gun",
        "image_url": ""
    },
    {
        "id": "electric-cupping-therapy-suction-gun",
        "name": "Electric Cupping Therapy Suction Gun",
        "category": "Hijama Suction Gun",
        "price": 450,
        "old_price": 750,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Rechargeable electric cupping therapy suction gun.",
        "keywords": ["electric", "cupping", "suction gun", "rechargeable", "hijama"],
        "product_url": "/product/electric-cupping-therapy-suction-gun",
        "image_url": ""
    },
    {
        "id": "hijama-vacuum-gun-milky-white",
        "name": "Hijama Vacuum Gun (Milky White)",
        "category": "Hijama Suction Gun",
        "price": 130,
        "old_price": 370,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Milky white hijama vacuum gun for cupping therapy.",
        "keywords": ["hijama", "vacuum gun", "milky white", "cupping pump"],
        "product_url": "/product/hijama-vacuum-gun-milky-white",
        "image_url": ""
    },
    {
        "id": "black-hijama-suction-gun",
        "name": "Black Hijama Suction Gun",
        "category": "Hijama Suction Gun",
        "price": 179,
        "old_price": 279,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Black cupping vacuum pump for hijama cupping therapy.",
        "keywords": ["black hijama gun", "suction gun", "cupping vacuum pump"],
        "product_url": "/product/black-hijama-suction-gun",
        "image_url": ""
    },

    # ---------------- Cupping Therapy Essentials ----------------
    {
        "id": "professional-korean-vacuum-cupping-set",
        "name": "New Professional Korean Vacuum Cupping Set With Cupping Gun",
        "category": "Cupping Therapy Essentials",
        "price": 2800,
        "old_price": 3111,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Complete professional cupping set with multiple high-quality vacuum cups and suction gun.",
        "keywords": ["korean cupping set", "vacuum cupping set", "hijama kit", "cupping gun"],
        "product_url": "/product/professional-korean-vacuum-cupping-set",
        "image_url": ""
    },
    {
        "id": "hijama-cup-size-1-set-10",
        "name": "Hijama Cup | Size 1 | Cupping Therapy | Set of 10 Pcs",
        "category": "Cupping Therapy Essentials",
        "price": 99,
        "old_price": 149,
        "discount": "40% off",
        "rating": 4.0,
        "description": "Size 1 hijama cups set of 10 pieces for cupping therapy.",
        "keywords": ["hijama cup", "size 1", "cupping cups", "set of 10"],
        "product_url": "/product/hijama-cup-size-1-set-10",
        "image_url": ""
    },
    {
        "id": "hijama-cup-size-2-set-10",
        "name": "Hijama Cup | Size 2 | Cupping Therapy | Set of 10 Pcs",
        "category": "Cupping Therapy Essentials",
        "price": 99,
        "old_price": 149,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Size 2 premium quality cupping therapy cup set of 10 pieces.",
        "keywords": ["hijama cup", "size 2", "cupping cups", "set of 10"],
        "product_url": "/product/hijama-cup-size-2-set-10",
        "image_url": ""
    },
    {
        "id": "hijama-cup-size-3-set-10",
        "name": "Hijama Cup | Size 3 | Cupping Therapy | Set of 10 Pcs",
        "category": "Cupping Therapy Essentials",
        "price": 99,
        "old_price": 149,
        "discount": "40% off",
        "rating": 4.0,
        "description": "Size 3 premium quality cupping therapy cup set of 10 pieces.",
        "keywords": ["hijama cup", "size 3", "cupping cups", "set of 10"],
        "product_url": "/product/hijama-cup-size-3-set-10",
        "image_url": ""
    },
    {
        "id": "hijama-cup-size-4-set-10",
        "name": "Hijama Cup | Size 4 | Cupping Therapy | Set of 10 Pcs",
        "category": "Cupping Therapy Essentials",
        "price": 99,
        "old_price": 149,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Size 4 hijama cups for whole body cupping therapy.",
        "keywords": ["hijama cup", "size 4", "cupping cups", "whole body"],
        "product_url": "/product/hijama-cup-size-4-set-10",
        "image_url": ""
    },
    {
        "id": "bamboo-cupping-therapy-set-3-cup",
        "name": "Bamboo Cupping Therapy Set - 3 Cup Set",
        "category": "Cupping Therapy Essentials",
        "price": 599,
        "old_price": 699,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Bamboo cupping therapy set with 3 cups.",
        "keywords": ["bamboo cupping", "cupping set", "therapy cup", "natural"],
        "product_url": "/product/bamboo-cupping-therapy-set-3-cup",
        "image_url": ""
    },
    {
        "id": "fire-glass-cupping-set-16",
        "name": "Fire Glass Cupping Therapy Set | Fire Glass 16 Cup Set",
        "category": "Cupping Therapy Essentials",
        "price": 899,
        "old_price": 999,
        "discount": "0% off",
        "rating": 4.0,
        "description": "Fire glass cupping therapy set with 16 glass cups.",
        "keywords": ["fire glass", "glass cupping", "cupping set", "16 cups"],
        "product_url": "/product/fire-glass-cupping-set-16",
        "image_url": ""
    },
    {
        "id": "professional-hijama-cupping-set-size-1-2",
        "name": "Hijama Cupping Set | Professional Cupping Therapy | Size 1,2 Set",
        "category": "Cupping Therapy Essentials",
        "price": 399,
        "old_price": 499,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Professional hijama cupping therapy set with size 1 and size 2 cups.",
        "keywords": ["professional cupping set", "hijama kit", "size 1", "size 2"],
        "product_url": "/product/professional-hijama-cupping-set-size-1-2",
        "image_url": ""
    },

    # ---------------- Microneedling Device ----------------
    {
        "id": "lancet-pen-3-pin-hijama-tool",
        "name": "Lancet Pen (3 Pin) For Cupping Therapy | Hijama Tool",
        "category": "Microneedling Device",
        "price": 599,
        "old_price": 669,
        "discount": "10% off",
        "rating": 4.0,
        "description": "3-pin lancet pen for wet cupping procedures with adjustable depth control and ergonomic pen design.",
        "keywords": ["lancet pen", "3 pin", "hijama tool", "wet cupping", "microneedling"],
        "product_url": "/product/lancet-pen-3-pin-hijama-tool",
        "image_url": ""
    },
    {
        "id": "dr-pen-ultima-m8",
        "name": "Dr Pen Ultima M8 Microneedling Derma Device",
        "category": "Microneedling Device",
        "price": 3999,
        "old_price": 4499,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Dr Pen Ultima M8 microneedling derma device.",
        "keywords": ["dr pen", "m8", "microneedling", "derma pen", "skin"],
        "product_url": "/product/dr-pen-ultima-m8",
        "image_url": ""
    },
    {
        "id": "microneedling-a6-ultima-dermapen",
        "name": "Microneedling A6 Ultima Dermapen Acne Scars Wrinkles",
        "category": "Microneedling Device",
        "price": 3499,
        "old_price": 3999,
        "discount": "30% off",
        "rating": 4.0,
        "description": "A6 Ultima dermapen for microneedling category.",
        "keywords": ["a6", "dermapen", "microneedling", "acne scars", "wrinkles"],
        "product_url": "/product/microneedling-a6-ultima-dermapen",
        "image_url": ""
    },
    {
        "id": "n2w-derma-pen-wireless",
        "name": "Microneedling N2W Derma Pen Wireless Face Rejuvenation",
        "category": "Microneedling Device",
        "price": 3200,
        "old_price": 4500,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Wireless N2W derma pen for face rejuvenation category.",
        "keywords": ["n2w", "wireless derma pen", "microneedling", "face rejuvenation"],
        "product_url": "/product/n2w-derma-pen-wireless",
        "image_url": ""
    },
    {
        "id": "dr-pen-microneedling-cartridges",
        "name": "Dr. Pen Microneedling Cartridges",
        "category": "Microneedling Device",
        "price": 299,
        "old_price": 399,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Replacement cartridges for Dr. Pen. Available in 12 pin, 36 pin and nano types.",
        "keywords": ["dr pen cartridges", "12 pin", "36 pin", "nano", "microneedling"],
        "product_url": "/product/dr-pen-microneedling-cartridges",
        "image_url": ""
    },
    {
        "id": "zgts-derma-roller-05",
        "name": "ZGTS Professional Gold Plated 0.5 mm | Titanium Alloy Derma Roller",
        "category": "Microneedling Device",
        "price": 349,
        "old_price": 399,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Gold plated titanium alloy derma roller 0.5 mm.",
        "keywords": ["zgts", "derma roller", "0.5 mm", "titanium", "gold"],
        "product_url": "/product/zgts-derma-roller-05",
        "image_url": ""
    },
    {
        "id": "zgts-derma-roller-10",
        "name": "ZGTS Professional Gold Plated 1.0 mm | Titanium Alloy Derma Roller",
        "category": "Microneedling Device",
        "price": 349,
        "old_price": 449,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Gold plated titanium alloy derma roller 1.0 mm.",
        "keywords": ["zgts", "derma roller", "1.0 mm", "titanium", "gold"],
        "product_url": "/product/zgts-derma-roller-10",
        "image_url": ""
    },
    {
        "id": "zgts-derma-roller-15",
        "name": "ZGTS Professional Gold Plated 1.5 mm | Titanium Alloy Derma Roller",
        "category": "Microneedling Device",
        "price": 349,
        "old_price": 449,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Gold plated titanium alloy derma roller 1.5 mm.",
        "keywords": ["zgts", "derma roller", "1.5 mm", "titanium", "gold"],
        "product_url": "/product/zgts-derma-roller-15",
        "image_url": ""
    },
    {
        "id": "zgts-derma-roller-20",
        "name": "ZGTS Professional Gold Plated 2.0 mm | Titanium Alloy Derma Roller",
        "category": "Microneedling Device",
        "price": 349,
        "old_price": 449,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Gold plated titanium alloy derma roller 2.0 mm.",
        "keywords": ["zgts", "derma roller", "2.0 mm", "titanium", "gold"],
        "product_url": "/product/zgts-derma-roller-20",
        "image_url": ""
    },

    # ---------------- Infra Red Device ----------------
    {
        "id": "advanced-knee-massager",
        "name": "Advanced Knee Massager for Pain Relief Heat Vibration",
        "category": "Infra Red Device",
        "price": 4500,
        "old_price": 6105,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Advanced knee massager with heat and vibration functions.",
        "keywords": ["knee massager", "heat", "vibration", "infrared", "pain relief"],
        "product_url": "/product/advanced-knee-massager",
        "image_url": ""
    },
    {
        "id": "omega-infra-red-body-lamp",
        "name": "Omega Infra Red Body Stimulation Lamp Pain Relief",
        "category": "Infra Red Device",
        "price": 2599,
        "old_price": 4999,
        "discount": "30% off",
        "rating": 4.0,
        "description": "Infrared body stimulation lamp for therapy and wellness category.",
        "keywords": ["infrared lamp", "omega lamp", "body stimulation", "therapy lamp"],
        "product_url": "/product/omega-infra-red-body-lamp",
        "image_url": ""
    },
    {
        "id": "tera-care-device",
        "name": "Tera Care Device",
        "category": "Infra Red Device",
        "price": 2500,
        "old_price": 4220,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Tera care device in infrared and therapy device category.",
        "keywords": ["tera care", "infrared", "therapy device"],
        "product_url": "/product/tera-care-device",
        "image_url": ""
    },

    # ---------------- Surgical Items ----------------
    {
        "id": "disposable-bed-sheets-20gsm",
        "name": "Disposable Bed Sheets | Clinic Bed Sheets | 20 GSM | 6 x 3 ft",
        "category": "Surgical Items",
        "price": 536,
        "old_price": 850,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Disposable clinic bed sheets, 20 GSM, 6 x 3 ft.",
        "keywords": ["bed sheet", "clinic bed sheet", "disposable", "surgical"],
        "product_url": "/product/disposable-bed-sheets-20gsm",
        "image_url": ""
    },
    {
        "id": "sterile-surgical-blade-11",
        "name": "11 No. Sterile Surgical Blade | 100 Pcs Box",
        "category": "Surgical Items",
        "price": 467,
        "old_price": 690,
        "discount": "25% off",
        "rating": 4.0,
        "description": "No. 11 sterile surgical blade, 100 pieces box.",
        "keywords": ["surgical blade", "sterile blade", "11 number blade", "100 pcs"],
        "product_url": "/product/sterile-surgical-blade-11",
        "image_url": ""
    },
    {
        "id": "nitrile-disposable-gloves-100",
        "name": "Nitrile Disposable Gloves 100 Pcs Box",
        "category": "Surgical Items",
        "price": 269,
        "old_price": 299,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Powder-free nitrile examination gloves, box of 100. Suitable for medical, laboratory, cleaning and hygiene use.",
        "keywords": ["nitrile gloves", "disposable gloves", "clinic gloves", "100 pcs", "surgical"],
        "product_url": "/product/nitrile-disposable-gloves-100",
        "image_url": ""
    },
    {
        "id": "latex-hand-gloves-100",
        "name": "Hand Gloves (100 Pcs) Latex",
        "category": "Surgical Items",
        "price": 289,
        "old_price": 399,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Latex hand gloves, box of 100 pieces.",
        "keywords": ["latex gloves", "hand gloves", "100 pcs", "clinic"],
        "product_url": "/product/latex-hand-gloves-100",
        "image_url": ""
    },

    # ---------------- Body Massage Tools ----------------
    {
        "id": "moxa-cup-6-pcs",
        "name": "Natural Healing | Moxa Cup | 6 Pcs Set",
        "category": "Body Massage Tools",
        "price": 3049,
        "old_price": 4099,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Moxa cup set of 6 pieces for natural healing and body therapy category.",
        "keywords": ["moxa cup", "massage", "body therapy", "natural healing"],
        "product_url": "/product/moxa-cup-6-pcs",
        "image_url": ""
    },
    {
        "id": "iastm-massage-tools-6pcs",
        "name": "Deep Tissue IASTM Massage Tools 6 Pcs Kit Stainless Steel",
        "category": "Body Massage Tools",
        "price": 2500,
        "old_price": 3990,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Stainless steel IASTM massage tools kit for deep tissue massage category.",
        "keywords": ["iastm", "deep tissue", "massage tools", "stainless steel"],
        "product_url": "/product/iastm-massage-tools-6pcs",
        "image_url": ""
    },
    {
        "id": "electric-acupressure-massage-pen",
        "name": "Electric Acupressure Massage Pen Acu Pen",
        "category": "Body Massage Tools",
        "price": 4399,
        "old_price": 5800,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Electric acupressure massage pen.",
        "keywords": ["acupressure pen", "acu pen", "massage pen", "electric"],
        "product_url": "/product/electric-acupressure-massage-pen",
        "image_url": ""
    },
    {
        "id": "silicon-body-massager-cup-set-4pcs",
        "name": "Silicon Body Massager Cup Set | 4 Pcs Moving Body Massage Cup",
        "category": "Body Massage Tools",
        "price": 599,
        "old_price": 649,
        "discount": "30% off",
        "rating": 3.0,
        "description": "Silicone body massager cup set of 4 pieces.",
        "keywords": ["silicone cup", "body massager", "massage cup", "cupping"],
        "product_url": "/product/silicon-body-massager-cup-set-4pcs",
        "image_url": ""
    },
    {
        "id": "wooden-therapy-massage-tool-set-10",
        "name": "Wooden Therapy Massage Tool Set 10 Pieces",
        "category": "Body Massage Tools",
        "price": 1300,
        "old_price": 1350,
        "discount": "0% off",
        "rating": 4.0,
        "description": "Wooden therapy massage tools for acupressure, gua sha, reflexology and trigger point massage.",
        "keywords": ["wooden massage", "gua sha", "reflexology", "trigger point", "acupressure"],
        "product_url": "/product/wooden-therapy-massage-tool-set-10",
        "image_url": ""
    },

    # ---------------- Trichology ----------------
    {
        "id": "dermaheal-prp-tube",
        "name": "Buy Dermaheal PRP Tube for Hair and Skin Platelet Rich Plasma",
        "category": "Trichology",
        "price": 456,
        "old_price": 758,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Dermaheal PRP tube for hair and skin category.",
        "keywords": ["prp tube", "dermaheal", "hair", "skin", "trichology"],
        "product_url": "/product/dermaheal-prp-tube",
        "image_url": ""
    },
    {
        "id": "dermaheal-gfc-tube",
        "name": "Buy Dermaheal GFC Tube Online Best for Hair Loss Treatment Shop",
        "category": "Trichology",
        "price": 1260,
        "old_price": 1500,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Dermaheal GFC tube for hair and trichology category.",
        "keywords": ["gfc tube", "dermaheal", "hair", "trichology"],
        "product_url": "/product/dermaheal-gfc-tube",
        "image_url": ""
    },

    # ---------------- Facial Serum / Beauty ----------------
    {
        "id": "vitamin-c-serum",
        "name": "Best Vitamin C Serum Antiaging Face Serum Radiant Skin",
        "category": "Facial Serum",
        "price": 250,
        "old_price": 470,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Vitamin C antiaging face serum for radiant skin category.",
        "keywords": ["vitamin c serum", "face serum", "antiaging", "radiant skin"],
        "product_url": "/product/vitamin-c-serum",
        "image_url": ""
    },
    {
        "id": "facial-serum-sheets-mask-combo",
        "name": "Facial Serum Sheets Mask 6 in 1 Combo Free Delivery",
        "category": "Facial Serum",
        "price": 210,
        "old_price": 280,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Facial serum sheet mask 6 in 1 combo.",
        "keywords": ["sheet mask", "facial serum", "mask combo", "beauty"],
        "product_url": "/product/facial-serum-sheets-mask-combo",
        "image_url": ""
    },
    {
        "id": "retinol-facial-serum",
        "name": "Retinol Facial Serum Antiaging Serum",
        "category": "Facial Serum",
        "price": 269,
        "old_price": 369,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Retinol serum with vitamin A and hyaluronic acid for antiaging skincare category.",
        "keywords": ["retinol", "facial serum", "antiaging", "hyaluronic acid"],
        "product_url": "/product/retinol-facial-serum",
        "image_url": ""
    },
    {
        "id": "hyaluronic-serum",
        "name": "Hyaluronic Serum",
        "category": "Beauty Products",
        "price": 250,
        "old_price": None,
        "discount": "0% off",
        "rating": 4.0,
        "description": "Hyaluronic serum in beauty products category.",
        "keywords": ["hyaluronic serum", "beauty", "skincare"],
        "product_url": "/product/hyaluronic-serum",
        "image_url": ""
    },

    # ---------------- Vacuum / Beauty Machines ----------------
    {
        "id": "vacuum-cupping-therapy-24pcs",
        "name": "Vacuum Cupping Therapy | 24 Pcs Body Slimming Tools",
        "category": "Vacuum Therapy Machine",
        "price": 8999,
        "old_price": 9999,
        "discount": "23% off",
        "rating": 4.0,
        "description": "Professional vacuum therapy machine with 24 body slimming tools. Suitable for clinic category.",
        "keywords": ["vacuum therapy", "body slimming", "cupping machine", "clinic"],
        "product_url": "/product/vacuum-cupping-therapy-24pcs",
        "image_url": ""
    },
    {
        "id": "diamond-dermabrasion-machine",
        "name": "Diamond Dermabrasion Machine With Tools",
        "category": "Vacuum Therapy Machine",
        "price": 5999,
        "old_price": 6499,
        "discount": "30% off",
        "rating": 3.0,
        "description": "Diamond dermabrasion machine with tools.",
        "keywords": ["diamond dermabrasion", "beauty machine", "skin machine"],
        "product_url": "/product/diamond-dermabrasion-machine",
        "image_url": ""
    },
    {
        "id": "portable-frequency-facial-device",
        "name": "Portable Frequency Facial Device | Skin Therapy | Acne",
        "category": "Beauty Machine",
        "price": 1549,
        "old_price": 1609,
        "discount": "30% off",
        "rating": 4.0,
        "description": "Portable high frequency facial device for skin therapy category.",
        "keywords": ["facial device", "high frequency", "skin therapy", "beauty machine"],
        "product_url": "/product/portable-frequency-facial-device",
        "image_url": ""
    },
    {
        "id": "energy-beauty-bar-24k",
        "name": "Energy Beauty Bar 24k Combo Electric",
        "category": "Beauty Machine",
        "price": 1300,
        "old_price": 1600,
        "discount": "30% off",
        "rating": 4.0,
        "description": "24k energy beauty bar combo electric device.",
        "keywords": ["beauty bar", "24k", "electric", "beauty device"],
        "product_url": "/product/energy-beauty-bar-24k",
        "image_url": ""
    },

    # ---------------- Portable Massage Bed ----------------
    {
        "id": "portable-2-fold-massage-bed",
        "name": "Portable 2 Fold Massage Bed | Massage Therapy Bed",
        "category": "Portable Massage Bed",
        "price": 8999,
        "old_price": 9499,
        "discount": "30% off",
        "rating": 3.0,
        "description": "Portable 2 fold massage therapy bed.",
        "keywords": ["massage bed", "portable bed", "therapy bed", "2 fold"],
        "product_url": "/product/portable-2-fold-massage-bed",
        "image_url": ""
    },
    {
        "id": "portable-3-fold-massage-bed",
        "name": "Best Quality Portable 3 Fold Massage Bed",
        "category": "Portable Massage Bed",
        "price": 10000,
        "old_price": 10500,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Best quality portable 3 fold massage bed.",
        "keywords": ["massage bed", "portable bed", "3 fold", "therapy bed"],
        "product_url": "/product/portable-3-fold-massage-bed",
        "image_url": ""
    },
    {
        "id": "portable-hijama-chair",
        "name": "Portable Hijama Chair | Folding Massage Spa Chair",
        "category": "Portable Massage Bed",
        "price": 5470,
        "old_price": 7500,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Portable folding hijama and massage spa chair.",
        "keywords": ["hijama chair", "massage chair", "folding chair", "spa chair"],
        "product_url": "/product/portable-hijama-chair",
        "image_url": ""
    },

    # ---------------- Smart Body Massager / Fitness ----------------
    {
        "id": "ems-foot-massager-pad",
        "name": "EMS Foot Massager Pad | Acupressure Massage Pad",
        "category": "Smart Body Massager",
        "price": 2200,
        "old_price": 2500,
        "discount": "20% off",
        "rating": 4.0,
        "description": "EMS foot massager pad with acupressure massage category.",
        "keywords": ["ems", "foot massager", "acupressure pad", "massage pad"],
        "product_url": "/product/ems-foot-massager-pad",
        "image_url": ""
    },
    {
        "id": "electric-cupping-massage-dynamic",
        "name": "Electric Cupping Massage Dynamic Cupping",
        "category": "Smart Body Massager",
        "price": 300,
        "old_price": 500,
        "discount": "10% off",
        "rating": 3.0,
        "description": "Electric dynamic cupping massage device.",
        "keywords": ["electric cupping", "dynamic cupping", "massage", "smart massager"],
        "product_url": "/product/electric-cupping-massage-dynamic",
        "image_url": ""
    },
    {
        "id": "smart-vibrating-massage-device",
        "name": "Smart Vibrating Massage Device | Digital Vibrator",
        "category": "Smart Body Massager",
        "price": 1090,
        "old_price": 1200,
        "discount": "20% off",
        "rating": 4.0,
        "description": "Smart vibrating digital massage device.",
        "keywords": ["vibrating massager", "digital massager", "smart massager"],
        "product_url": "/product/smart-vibrating-massage-device",
        "image_url": ""
    },
    {
        "id": "powerful-32-speed-massage-gun",
        "name": "Powerful 32 Speed Body Massage Gun Facial Gun Deep",
        "category": "Smart Body Massager",
        "price": 1499,
        "old_price": 1699,
        "discount": "20% off",
        "rating": 3.0,
        "description": "32 speed body massage gun for deep massage category.",
        "keywords": ["massage gun", "32 speed", "body massage", "deep massage"],
        "product_url": "/product/powerful-32-speed-massage-gun",
        "image_url": ""
    },
    {
        "id": "foot-massager-device",
        "name": "Health Protection | Foot Massager Device",
        "category": "Smart Body Massager",
        "price": 4999,
        "old_price": 5499,
        "discount": "0% off",
        "rating": 4.0,
        "description": "Foot massager device for relaxation category.",
        "keywords": ["foot massager", "health protection", "massage device"],
        "product_url": "/product/foot-massager-device",
        "image_url": ""
    },
    {
        "id": "physio-foam-roller",
        "name": "Physio Foam Roller",
        "category": "Fitness Equipment",
        "price": 349,
        "old_price": 499,
        "discount": "0% off",
        "rating": 4.0,
        "description": "Foam roller for muscle relaxation, recovery, physiotherapy, yoga and fitness training.",
        "keywords": ["foam roller", "physio", "fitness", "muscle recovery", "yoga"],
        "product_url": "/product/physio-foam-roller",
        "image_url": ""
    },
    {
        "id": "home-workout-pedal-exerciser",
        "name": "Home Workout Pedal Exerciser | Multi-functional Display",
        "category": "Fitness Equipment",
        "price": 1650,
        "old_price": 2000,
        "discount": "20% off",
        "rating": 3.0,
        "description": "Home workout pedal exerciser with multi-functional display.",
        "keywords": ["pedal exerciser", "home workout", "fitness equipment"],
        "product_url": "/product/home-workout-pedal-exerciser",
        "image_url": ""
    },

    # ---------------- Sauna / Face Massage / Acupuncture ----------------
    {
        "id": "portable-foot-massager-tub",
        "name": "Portable Foot Massager Tub | Deep Folding Tub",
        "category": "Sauna Steam Bath",
        "price": 600,
        "old_price": 750,
        "discount": "30% off",
        "rating": 4.0,
        "description": "Portable folding foot massager tub.",
        "keywords": ["foot tub", "foot massager", "portable tub", "sauna"],
        "product_url": "/product/portable-foot-massager-tub",
        "image_url": ""
    },
    {
        "id": "facial-massage-cup",
        "name": "Facial Massage Cup | Silicon Face Rejuvenation Cups",
        "category": "Facial Massage Tools",
        "price": 200,
        "old_price": 250,
        "discount": "20% off",
        "rating": 4.0,
        "description": "Silicone facial massage cup for face rejuvenation category.",
        "keywords": ["facial cup", "silicone cup", "face massage", "rejuvenation"],
        "product_url": "/product/facial-massage-cup",
        "image_url": ""
    },
    {
        "id": "electric-acupuncture-pen",
        "name": "Electric Acupuncture Pen - Points Detector Pen",
        "category": "Acupuncture Needles",
        "price": 590,
        "old_price": 660,
        "discount": "20% off",
        "rating": 4.0,
        "description": "Electric acupuncture points detector pen.",
        "keywords": ["acupuncture pen", "points detector", "electric pen", "acupressure"],
        "product_url": "/product/electric-acupuncture-pen",
        "image_url": ""
    },
    {
        "id": "acupuncture-needles-100-box",
        "name": "Acupuncture Needles | 100 Pcs Box",
        "category": "Acupuncture Needles",
        "price": 220,
        "old_price": 280,
        "discount": "20% off",
        "rating": 4.0,
        "description": "Acupuncture needles box of 100 pieces.",
        "keywords": ["acupuncture needles", "100 pcs", "therapy needles"],
        "product_url": "/product/acupuncture-needles-100-box",
        "image_url": ""
    },

    # ---------------- Books / Unani / Misc ----------------
    {
        "id": "practical-prescriber-book",
        "name": "Practical Prescriber",
        "category": "Hijama & Healthcare Books",
        "price": 500,
        "old_price": 850,
        "discount": "25% off",
        "rating": 4.0,
        "description": "Ayurveda healthcare book.",
        "keywords": ["book", "healthcare", "ayurveda", "practical prescriber"],
        "product_url": "/product/practical-prescriber-book",
        "image_url": ""
    },
    {
        "id": "bimariyan-harenge-book",
        "name": "Bimariyan Harenge",
        "category": "Hijama & Healthcare Books",
        "price": 50,
        "old_price": 670,
        "discount": "22% off",
        "rating": 4.0,
        "description": "Healthcare book category.",
        "keywords": ["book", "healthcare", "bimariyan", "hindi"],
        "product_url": "/product/bimariyan-harenge-book",
        "image_url": ""
    },
    {
        "id": "khurmee-350gm",
        "name": "Khurmee | 350gm | Healthy & Natural Ingredients",
        "category": "Unani Remedy",
        "price": 180,
        "old_price": 350,
        "discount": "25% off",
        "rating": 3.0,
        "description": "Khurmee 350gm natural ingredients product.",
        "keywords": ["khurmee", "unani", "natural", "350gm"],
        "product_url": "/product/khurmee-350gm",
        "image_url": ""
    },
    {
        "id": "memory-pillow",
        "name": "Memory Pillow | Relaxation | Sleep",
        "category": "More Items",
        "price": 549,
        "old_price": 700,
        "discount": "10% off",
        "rating": 4.0,
        "description": "Memory pillow for relaxation and sleep.",
        "keywords": ["memory pillow", "sleep", "relaxation", "pillow"],
        "product_url": "/product/memory-pillow",
        "image_url": ""
    }
]